### ISSUE TITLE
 returned a non-zero code: 2 while build in BASE image rust:1.61.0-buster

### ISSUE THREAD

**Issue by arayalways** [helium/blockchain-node#136] opened 2022-05-21 01:52 UTC
===> Failed to fetch and copy dep: {git,
                                  "https://github.com/novalabsxyz/grpcbox.git",
                                  {ref,
                                      "5cca01a52b6bb4c8dbadf1fe7f6441a350308235"}}
make: *** [Makefile:18: compile] Error 1

**Comment by madninja** [comment] 2022-05-21 02:12
Please try again with the latest master branch

**Comment by madninja** [comment] 2022-05-21 02:16
perhaps not.. looking

**Comment by jasonhe-github** [comment] 2022-05-21 02:48
I got a similar error:
`===> Fetching grpcbox (from {git,"https://github.com/novalabsxyz/grpcbox.git",
                   {ref,"5cca01a52b6bb4c8dbadf1fe7f6441a350308235"}})
===> Failed to fetch and copy dep: {git,
                                  "https://github.com/novalabsxyz/grpcbox.git",
                                  {ref,
                                      "5cca01a52b6bb4c8dbadf1fe7f6441a350308235"}}
The command '/bin/sh -c ./rebar3 compile' returned a non-zero code: 1
Makefile:56: recipe for target 'docker-build' failed
make: *** [docker-build] Error 1`
I don't know how to solve this problem!

**Comment by joslee7410** [comment] 2022-05-21 03:35
#135 I think we getting same error

**Comment by madninja** [comment] 2022-05-21 04:07
Yeah, I see the issue.. will get it fixed up shortly with a new core git ref. 

I'll close this as a dupe of #135

**Comment by joslee7410** [comment] 2022-05-21 04:08
> 

Thank you Sir.

**Closed as completed** 2022-05-21 04:08 UTC

**Comment by arayalways** [comment] 2022-05-21 14:19
Thank you
